### ISSUE TITLE
1.7.0 requires abandoned packages

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-modal#2]
The following packages are marked as abandoned and shouldn't be used, but are still required by contao-modal:
`	"heimrichhannot/contao-ajax": "^1.0.13",
	"heimrichhannot/contao-be_explanation": "~1.0",
	"heimrichhannot/contao-teaser": "~1.0",`

Could you please change those to the "bundled" versions!?
Thanks.

**Comment by koertho** [comment]
@DrAColian Since this is a contao 3 module, we can't upgrade the dependencies to the bundle versions.

**Comment by koertho** [comment]
@DrAColian Just want to add, that contao-teaser-bundle and contao-be_explanation-bundle replace the modules, so you would have less abandoned packages.
